import Lean
import {{MODULE}}

/-!
Generated by `scripts/verify.py`; do not edit by hand.

Imports the submitted module and prints one JSON line, prefixed by
`PROOFCOMMONS_JSON`, listing every declaration of that module with its kind,
whether its type is definitionally equal to the registered statement, and the
axioms it depends on. The policy (allowed axioms, namespace) is applied by the
Python side; this file only reports.
-/

open Lean Meta Elab Command in
run_cmd do
  let env ← getEnv
  let modName : Name := `{{MODULE}}
  let target : Name := `{{STATEMENT}}
  unless env.contains target do
    throwError "statement constant {target} not found in the environment"
  let some modIdx := env.getModuleIdx? modName
    | throwError "module {modName} not found in the environment"
  let names := env.header.moduleData[modIdx.toNat]!.constNames
  let targetE := mkConst target
  let mut out : Array Json := #[]
  for n in names do
    if n.isInternalDetail || isAuxRecursor env n || isNoConfusion env n || isRecCore env n then
      continue
    let ci ← getConstInfo n
    let kind := match ci with
      | .thmInfo _ => "theorem" | .defnInfo _ => "def" | .axiomInfo _ => "axiom"
      | .opaqueInfo _ => "opaque" | .inductInfo _ => "inductive" | .ctorInfo _ => "constructor"
      | .recInfo _ => "recursor" | .quotInfo _ => "quot"
    let proves ← liftTermElabM <| withoutModifyingState <| Meta.isDefEq ci.type targetE
    let axs ← collectAxioms n
    out := out.push <| Json.mkObj [
      ("name", toString n), ("kind", kind), ("proves_statement", toJson proves),
      ("axioms", toJson (axs.map toString))]
  let payload := Json.mkObj [("module", toString modName), ("statement", toString target),
                             ("declarations", Json.arr out)]
  IO.println s!"PROOFCOMMONS_JSON {payload.compress}"
